# Generated by Django 3.2.14 on 2022-09-10 16:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('phone', models.CharField(max_length=50)),
                ('dateofbirth', models.DateField(default=datetime.date.today)),
                ('img', models.ImageField(default='img', upload_to='')),
                ('wallet_balance', models.CharField(max_length=20)),
            ],
        ),
    ]
