# Generated by Django 3.2.14 on 2022-09-08 09:34

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PaymentProve',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=50)),
                ('amount', models.IntegerField()),
                ('image', models.ImageField(default='img', upload_to='')),
                ('date_posted', models.DateTimeField(default=django.utils.timezone.now)),
                ('checked', models.BooleanField(default=False)),
            ],
        ),
    ]
