# Generated by Django 3.2.14 on 2022-09-09 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wallet', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paymentprove',
            name='date_posted',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
